### ISSUE TITLE
[Bug] Server won't stop because of a waiting FileWatcher thread

### ISSUE THREAD

**Issue by realkarmakun** [SuperMartijn642/SuperMartijn642sConfigLib#21]
**Version Info**
- Minecraft, 1.20.1
- NeoForge, 47.1.100
- Config Lib, 1.1.8

**Server Info**
- Linux (tried both openjdk slim docker image) and Manjaro
- Java Temurin 17.0.10

**Description of the Bug**
When server is stopped, it will but few threads will be left hanging unallowing for the server process to completely shutdown. Here is a bit of logs along with threadumps produced after: https://ptero.co/hinovepejo.pl
 

**Steps to Reproduce**
Run Linux with Java Temurin. Install the lib along with the mod that uses it. I was able to reproduce it perhaps the exact issue is with one of dependable mods, but that's yet to be confirmed

**Screenshots**
None

**Comment by SuperMartijn642** [comment]
There appears to be only a single thread from my config library which is marked as 'daemon'.
![image](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/assets/12382965/8df5a913-668e-4ecb-9ea6-19fb8e2e21e3)
Daemon threads will not prevent the Java program from exiting.
Are you sure this is caused by my core library? What other mods are needed to reproduce this?

**Comment by realkarmakun** [comment]
Yeah sorry, perhaps I was hasty making and issue, but this thread dumps are of a single process that is left hanging after stopping the server. Maybe some mod depending on the library is not using it correctly. I'll try binary searching for it, though I believe it's still connected to the library. Can we not close the issue for the time being?

**Comment by realkarmakun** [comment]
UPD: Actually I don't really have time searching for dependencies to this mod, so I guess I can just deal with it. I'll be closing this
